### ISSUE TITLE
Virtual Machine list page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/harvester-ui#185]
- [x] Change top title from VirtualMachines to Virtual Machines
![image](https://user-images.githubusercontent.com/11514927/98871018-73385080-2431-11eb-9f8c-c3e8c2e0209d.png)

- [x] Change left menu pane from Virtual Machine to Virtual Machines (add the s)
![image](https://user-images.githubusercontent.com/11514927/98871030-792e3180-2431-11eb-8d21-1fef2d40e3af.png)

- [ ] Remove the console drop-down button and put the two actions in the action menu for each VM

Move this:
 ![image](https://user-images.githubusercontent.com/11514927/98871045-7f241280-2431-11eb-8914-500bb3b164cc.png)

Into here:
![image](https://user-images.githubusercontent.com/11514927/98871122-a549b280-2431-11eb-9b58-b3bb2c3af471.png)

- [x] Why is there a namespace field?  Can I change where it is going?  I didn't see that in the Create?  If it's always going to be the same and I can't switch it can we remove this field?

**Comment by guangbochen** [comment]
> Remove the console drop-down button and put the two actions in the action menu for each VM

this is done in-purpose since we need to support both VNC and the serial console as some guest OS may only have one type of the console mode, and literary they are not part of the VM actions so would prefer to keep the current design, however, the font size is quite small on my 2560 x 1440 screen resolution, @DaiYuzeng can u please help to check it, thanks.

**Comment by WuJun2016** [comment]
Console bar font issues have been fixed.

**Comment by tfiduccia** [comment]
Fixed.
