### ISSUE TITLE
Remove progress from image list view

### ISSUE THREAD

**Issue by tfiduccia** [rancher/harvester-ui#191]
- [x] Remove progress, the state should show if it's still in progress and it's worthless once it's uploaded.
![image](https://user-images.githubusercontent.com/11514927/98876658-fc548500-243b-11eb-8712-078b9709c78e.png)

**Comment by DaiYuzeng** [comment]
The progress will be removed when the image successfully imported. And the field will display "Completed".
If the image imported failed, error message will instead of progress to display.
![截屏2020-11-13 下午3 08 54](https://user-images.githubusercontent.com/15041915/99039351-2932a480-25c2-11eb-9b87-f6227b84d4e4.png)

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester-ui/pull/203

**Comment by tfiduccia** [comment]
I verified that this is working correctly.
